// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1gr8fAPcuYQZsrsPli-Cr5XdaQxKiBnM',
    appId: '1:287027130435:android:cce647ff2da8aecd00e4f6',
    messagingSenderId: '287027130435',
    projectId: 'push-notify-6767',
    storageBucket: 'push-notify-6767.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-hDqlyTPuZ6t6hIsktKg41yX4kbWqLCk',
    appId: '1:287027130435:ios:6cd1d8be7609ed4e00e4f6',
    messagingSenderId: '287027130435',
    projectId: 'push-notify-6767',
    storageBucket: 'push-notify-6767.appspot.com',
    iosBundleId: 'com.example.skorpioapiintegration',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuXt0btWV5kQw8C6PvD4EdwPA36pvbto4',
    appId: '1:880377475429:web:68fb83ce665a18db7f718c',
    messagingSenderId: '880377475429',
    projectId: 'skorpio-88118',
    authDomain: 'skorpio-88118.firebaseapp.com',
    storageBucket: 'skorpio-88118.appspot.com',
    measurementId: 'G-5FZSLZKTFJ',
  );

}